export const POSITION_ALIASES: Record<string, string> = {
  // Mainstream High-Volume Aliases -> Canonical Position IDs
  'doggy-style': 'arch-anchor',
  'doggy-position': 'arch-anchor',
  'rear-entry': 'arch-anchor',
  'cowgirl': 'overdrive-cowgirl',
  'cowgirl-position': 'overdrive-cowgirl',
  'woman-on-top': 'overdrive-cowgirl',
  'reverse-cowgirl': 'reverse-cowgirl-arch',
  'missionary': 'royal-arch',
  'missionary-position': 'royal-arch',
  'coital-alignment-technique': 'royal-arch',
  'cat-position': 'royal-arch',
  'amazon': 'amazon-straddle',
  'amazon-position': 'amazon-straddle',
  'amazon-sex-position': 'amazon-straddle',
  'spooning': 'lazy-sunday',
  'spooning-position': 'lazy-sunday',
  'side-by-side': 'lazy-sunday',
  'lotus-position': 'lotus-lock',
  'seated-lotus': 'lotus-lock',
  'standing-against-wall': 'wall-pin',
  'standing-sex-position': 'wall-pin',
  'standing-position': 'wall-pin',
  'waterfall': 'waterfall-arch',
  'waterfall-position': 'waterfall-arch',
  'sovereign-squat': 'sovereign-squat',
}
